import test from "node:test";
import assert from "node:assert/strict";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import ejs from "ejs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const templatePath = path.join(
  __dirname,
  "../templates/tolk_verifier_groth16.ejs",
);

const dummyG1 = "a0" + "11".repeat(47);
const dummyG2 = "b0" + "22".repeat(95);

async function renderTemplate(nPublic, contractName) {
  const template = await fs.readFile(templatePath, "utf8");
  return ejs.render(template, {
    protocol: "groth16",
    curve: "bn128",
    contractName,
    vk_alpha_1: dummyG1,
    vk_beta_2: dummyG2,
    vk_gamma_2: dummyG2,
    vk_delta_2: dummyG2,
    IC: Array.from({ length: nPublic + 1 }, () => dummyG1),
    nPublic,
    publicInputKeyLen: 32,
  });
}

test("renders flat public input handling for small Groth16 circuits when contractName is omitted", async () => {
  const rendered = await renderTemplate(2);

  assert.match(rendered, /contract Verifier \{\s*description: "Groth16 verifier generated by export-ton-verifier"\s*storage: VerifierStorage\s*incomingMessages: Verify\s*\}/);
  assert.match(rendered, /struct VerifierStorage \{\}/);
  assert.match(rendered, /const IC0: slice/);
  assert.match(rendered, /fun groth16VerifyArray\(/);
  assert.match(rendered, /fun verifyProof\(msg: Verify\): bool/);
  assert.match(rendered, /struct \(0x3b3cca17\) Verify \{/);
  assert.match(rendered, /pubInputs: RemainingBitsAndRefs/);
  assert.match(rendered, /if \(pubInputs\.size\(\) != N_PUBLIC\)/);
  assert.match(rendered, /pubInputs\.get\(0\)/);
  assert.match(rendered, /pubInputs\.get\(1\)/);
  assert.match(rendered, /enum VerifierErrors \{\s*InvalidInputs = 258,\s*WrongProof = 260,\s*\}/);
  assert.match(rendered, /fun blsG1Multiexp2/);
  assert.match(rendered, /# Safety/);
  assert.match(rendered, /\.hexToSlice\(\)/);
  assert.match(rendered, /val y1: int = loadNextPubInput\(mutate payload\);/);
  assert.match(rendered, /val y2: int = loadNextPubInput\(mutate payload\);/);
  assert.match(rendered, /val piANeg: slice = blsG1Neg\(piA\);/);
  assert.match(rendered, /val ok: int = blsPairing\(/);
  assert.match(rendered, /val piA: slice = msg\.piA\.beginParse\(\);/);
  assert.match(rendered, /val piB: slice = msg\.piB\.beginParse\(\);/);
  assert.match(rendered, /val piC: slice = msg\.piC\.beginParse\(\);/);
  assert.match(rendered, /var payload: slice = msg\.pubInputs;/);
  assert.match(rendered, /loadNextPubInput\(mutate payload\)/);
  assert.match(rendered, /payload\.remainingBitsCount\(\) != 0 \|\| payload\.remainingRefsCount\(\) != 0/);
  assert.match(rendered, /fun onInternalMessage\(inMsg: InMessage\)/);
  assert.match(rendered, /assert \(verifyProof\(msg\)\) throw VerifierErrors\.WrongProof;/);
  assert.match(rendered, /assert \(inMsg\.body\.isEmpty\(\)\) throw VerifierErrors\.InvalidInputs;/);
  assert.match(rendered, /get fun verify\(piA: slice, piB: slice, piC: slice, pubInputs: array<int>\): bool/);
  assert.match(rendered, /return groth16VerifyArray\(piA, piB, piC, pubInputs\);/);
  assert.doesNotMatch(rendered, /struct MyVerifier \{/);
  assert.doesNotMatch(rendered, /get fun verify_/);

  assert.doesNotMatch(rendered, /@stdlib\/tvm-dicts/);
  assert.doesNotMatch(rendered, /stringHexToSlice/);
  assert.doesNotMatch(rendered, /uDictGet/);
  assert.doesNotMatch(rendered, /PUBLIC_KEY_LEN/);
  assert.doesNotMatch(rendered, /ERR_PUBLIC_NOT_PRESENT/);
  assert.doesNotMatch(rendered, /ERR_TOO_MANY_PUBLICS/);
  assert.doesNotMatch(rendered, /loadDict\(/);
  assert.doesNotMatch(rendered, /ERR_INDEX_OUT_OF_RANGE/);
  assert.doesNotMatch(rendered, /ERR_INVALID_INPUTS/);
  assert.doesNotMatch(rendered, /throw\(/);
  assert.doesNotMatch(rendered, /var y\d+: int =/);
  assert.doesNotMatch(rendered, /var piA: slice =/);
  assert.doesNotMatch(rendered, /var piB: slice =/);
  assert.doesNotMatch(rendered, /var piC: slice =/);
  assert.doesNotMatch(rendered, /var piANeg: slice =/);
  assert.doesNotMatch(rendered, /var ok: int =/);
});

test("renders struct mode with underscored getter when contractName is provided", async () => {
  const rendered = await renderTemplate(2, "MyVerifier");

  assert.match(rendered, /contract MyVerifier \{\s*description: "Groth16 verifier generated by export-ton-verifier"\s*storage: MyVerifierStorage\s*incomingMessages: MyVerifierVerify\s*\}/);
  assert.match(rendered, /struct MyVerifierStorage \{\}/);
  assert.match(rendered, /struct MyVerifier \{/);
  assert.match(rendered, /ic0: slice/);
  assert.match(rendered, /vkGamma2: slice/);
  assert.match(rendered, /nPublic: int/);
  assert.match(rendered, /fun MyVerifier\.create\(\): MyVerifier/);
  assert.match(rendered, /fun MyVerifier\.loadNextPubInput\(mutate payload: slice\): int/);
  assert.match(rendered, /MyVerifier\.loadNextPubInput\(mutate payload\)/);
  assert.match(rendered, /fun MyVerifier\.blsG1Multiexp2/);
  assert.match(rendered, /fun MyVerifier\.verify\(self, piA: slice, piB: slice, piC: slice, pubInputs: array<int>\): bool/);
  assert.match(rendered, /fun MyVerifier\.verifyProof\(self, msg: MyVerifierVerify\): bool/);
  assert.match(rendered, /struct \(0x3b3cca17\) MyVerifierVerify \{/);
  assert.match(rendered, /enum MyVerifierErrors \{\s*InvalidInputs = 258,\s*WrongProof = 260,\s*\}/);
  assert.match(rendered, /throw MyVerifierErrors\.InvalidInputs;/);
  assert.match(rendered, /assert \(MyVerifier\.create\(\)\.verifyProof\(msg\)\) throw MyVerifierErrors\.WrongProof;/);
  assert.match(rendered, /assert \(inMsg\.body\.isEmpty\(\)\) throw MyVerifierErrors\.InvalidInputs;/);
  assert.match(rendered, /get fun verify_MyVerifier\(piA: slice, piB: slice, piC: slice, pubInputs: array<int>\): bool/);
  assert.doesNotMatch(rendered, /get fun verify\(/);
  assert.doesNotMatch(rendered, /MY_VERIFIER_ERR_INVALID_INPUTS/);
});

test("renders runtime batches with inline IC selector for struct mode circuits with more than seven public inputs", async () => {
  const rendered = await renderTemplate(9, "MyVerifier");

  assert.match(rendered, /ic0: slice/);
  assert.match(rendered, /ic8: slice/);
  assert.match(rendered, /fun MyVerifier\.ic\(self, idx: int\): slice/);
  assert.match(rendered, /if \(idx == 8\) \{ return self\.ic8; \}/);
  assert.match(rendered, /IndexOutOfRange = 259/);
  assert.match(rendered, /throw MyVerifierErrors\.IndexOutOfRange;/);
  assert.match(rendered, /val full: int = self\.nPublic \/ 7/);
  assert.match(rendered, /val rem:\s+int = self\.nPublic % 7/);
  assert.match(rendered, /while \(done < full \* 7\)/);
  assert.match(rendered, /val tmp: slice = MyVerifier\.blsG1Multiexp7/);
  assert.match(rendered, /val tail: slice = MyVerifier\.blsG1Multiexp2/);
  assert.match(rendered, /MyVerifier\.blsG1Multiexp7/);
  assert.match(rendered, /MyVerifier\.blsG1Multiexp2/);
  assert.match(rendered, /self\.ic\(done \+ 1\), y1/);
  assert.match(rendered, /self\.ic\(done \+ 1\), pubInputs\.get\(done\)/);
  assert.match(rendered, /pubInputs\.get\(done \+ 1\)/);
  assert.match(rendered, /pubInputs: RemainingBitsAndRefs/);
  assert.match(rendered, /MyVerifierVerify\.fromSlice/);
  assert.match(rendered, /get fun verify_MyVerifier\(/);
  assert.doesNotMatch(rendered, /get fun verify\(/);

  assert.doesNotMatch(rendered, /fun pubInputAt\(/);
  assert.doesNotMatch(rendered, /uDictGet/);
  assert.doesNotMatch(rendered, /ERR_PUBLIC_NOT_PRESENT/);
  assert.doesNotMatch(rendered, /ERR_TOO_MANY_PUBLICS/);
  assert.doesNotMatch(rendered, /full -= 1/);
  assert.doesNotMatch(rendered, /var tmp: slice =/);
  assert.doesNotMatch(rendered, /var tail: slice =/);
});
