import test from "node:test";
import assert from "node:assert/strict";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import ejs from "ejs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const templatePath = path.join(
  __dirname,
  "../templates/tolk_verifier_plonk.ejs",
);

const dummyG1 = "a0" + "11".repeat(47);
const dummyG2 = "b0" + "22".repeat(95);
const dummyG1Uncompressed = "c0" + "33".repeat(95);

async function renderTemplate(nPublic, contractName) {
  const template = await fs.readFile(templatePath, "utf8");
  return ejs.render(template, {
    protocol: "plonk",
    curve: "bls12381",
    contractName,
    nPublic,
    power: 4,
    k1: "5",
    k2: "7",
    w: "13",
    Qm: dummyG1,
    Ql: dummyG1,
    Qr: dummyG1,
    Qo: dummyG1,
    Qc: dummyG1,
    S1: dummyG1,
    S2: dummyG1,
    S3: dummyG1,
    X_2: dummyG2,
    Qm_uc: dummyG1Uncompressed,
    Ql_uc: dummyG1Uncompressed,
    Qr_uc: dummyG1Uncompressed,
    Qo_uc: dummyG1Uncompressed,
    Qc_uc: dummyG1Uncompressed,
    S1_uc: dummyG1Uncompressed,
    S2_uc: dummyG1Uncompressed,
    S3_uc: dummyG1Uncompressed,
  });
}

test("renders PLONK verifier as Tolk contract instead of FunC", async () => {
  const rendered = await renderTemplate(2);

  assert.match(rendered, /contract Verifier \{\s*description: "PLONK verifier generated by export-ton-verifier"\s*storage: VerifierStorage\s*\}/);
  assert.match(rendered, /struct VerifierStorage \{\}/);
  assert.match(rendered, /type ScalarMap = map<uint32, uint256>/);
  assert.match(rendered, /enum VerifierErrors \{\s*PublicNotPresent = 101,\s*FailedInverse = 102,\s*ScalarNotInField = 103,\s*TooManyPublics = 104,\s*InvalidMessage = 105,\s*\}/);
  assert.match(rendered, /const QM: slice = "[a-f0-9]+".hexToSlice\(\)/);
  assert.match(rendered, /@pure\s+fun blsPairing\(/);
  assert.match(rendered, /fun int\.scalarToSlice\(self\): slice/);
  assert.match(rendered, /fun ScalarMap\.read\(self, i: int\): int/);
  assert.match(rendered, /fun ScalarMap\.setAt\(mutate self, i: int, v: int\): void/);
  assert.match(rendered, /fun checkPublicInputCount\(publicInputs: ScalarMap, nExpected: int\): void/);
  assert.match(rendered, /get fun verify\(/);
  assert.match(rendered, /publicInputs: ScalarMap/);
  assert.match(rendered, /checkField\(evalA\);/);
  assert.match(rendered, /while \(newr != 0\)/);
  assert.match(rendered, /while \(pi < N_PUBLIC\)/);
  assert.match(rendered, /betaHash\.push\(publicInputs\.read\(pi\)\.scalarToSlice\(\)\);/);
  assert.match(rendered, /checkPublicInputCount\(publicInputs, N_PUBLIC\);/);
  assert.match(rendered, /val evalL1: int = mulmod\(invd\.read\(1\), zh, blsR\(\)\);/);
  assert.doesNotMatch(rendered, /var evalL1: int/);
  assert.match(rendered, /return blsPairing\(blsG1Neg\(a1\), X_2, b1, BLS_G2\) != 0;/);
  assert.match(rendered, /fun onInternalMessage\(inMsg: InMessage\)/);
  assert.match(rendered, /assert \(inMsg\.body\.isEmpty\(\)\) throw VerifierErrors\.InvalidMessage;/);

  assert.doesNotMatch(rendered, /#include/);
  assert.doesNotMatch(rendered, /verifier::/);
  assert.doesNotMatch(rendered, /bls::/);
  assert.doesNotMatch(rendered, /recv_internal/);
  assert.doesNotMatch(rendered, /method_id/);
  assert.doesNotMatch(rendered, /throw\(/);
});

test("documents safety requirements for every PLONK Tolk asm helper", async () => {
  const rendered = await renderTemplate(2);
  const lines = rendered.split(/\r?\n/);

  for (const helper of [
    "blsPairing",
    "keccak256Tuple",
    "blsR",
    "mulmod",
    "blsG1Add",
    "blsG1Mul",
    "blsG1Sub",
    "blsG1Neg",
  ]) {
    const helperLine = lines.findIndex((line) =>
      line.includes(`fun ${helper}(`) && line.includes(' asm "'),
    );
    assert.notEqual(helperLine, -1, `${helper} asm declaration should render`);
    assert.match(
      lines.slice(Math.max(0, helperLine - 4), helperLine).join("\n"),
      /\/\/\/ # Safety/,
      `${helper} should have a nearby # Safety doc comment before its asm declaration`,
    );
  }
});

test("renders named PLONK contract metadata when contractName is provided", async () => {
  const rendered = await renderTemplate(0, "SecondVerifier");

  assert.match(rendered, /contract SecondVerifier \{\s*description: "PLONK verifier generated by export-ton-verifier"\s*storage: SecondVerifierStorage\s*\}/);
  assert.match(rendered, /struct SecondVerifierStorage \{\}/);
  assert.match(rendered, /enum SecondVerifierErrors \{/);
  assert.match(rendered, /throw SecondVerifierErrors\.FailedInverse;/);
  assert.match(rendered, /assert \(inMsg\.body\.isEmpty\(\)\) throw SecondVerifierErrors\.InvalidMessage;/);
  assert.match(rendered, /const N_PUBLIC: int = 0/);
  assert.match(rendered, /const N_LAGRANGE: int = 1/);
  assert.match(rendered, /get fun verify\(/);
  assert.doesNotMatch(rendered, /get fun verify_SecondVerifier/);
});
